name: snapnutrition
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  intl: ^0.18.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.7+3
  http: ^1.1.0  # Updated to be compatible with google_fonts
  fl_chart: ^0.70.2
  shared_preferences: ^2.2.2
  google_fonts: ^5.1.0
  flutter_markdown: ^0.6.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

executables:
  set_test_date: