name: snapnutrition
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  intl: ^0.20.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.1.2
  http: ^1.1.0  # Updated to be compatible with google_fonts
  fl_chart: ^0.71.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.2.1
  flutter_markdown: ^0.7.7
  barcode_scan2: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/barcode.webp


executables:
  set_test_date: